import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const words = JSON.parse(readFileSync(join(root, 'scripts', 'words-unique.json'), 'utf8'));

const POS = new Set(['noun', 'verb', 'adjective', 'adverb', 'preposition', 'conjunction', 'determiner', 'number', 'phrase']);
let all = [];
for (let p = 1; p <= 5; p++) {
  const part = JSON.parse(readFileSync(join(root, 'src', 'data', 'glosses', `part-${p}.json`), 'utf8'));
  all = all.concat(part);
}

const errors = [];
const slug = (w) => w.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
const seenSlugs = new Set();

if (all.length !== words.length) errors.push(`count mismatch: glosses=${all.length} dataset=${words.length}`);

for (let i = 0; i < words.length; i++) {
  const expected = words[i].word;
  const g = all[i];
  if (!g) { errors.push(`missing gloss at rank ${words[i].rank} (${expected})`); continue; }
  if (g.word !== expected) errors.push(`order/spelling mismatch at rank ${words[i].rank}: expected '${expected}', got '${g.word}'`);
  if (!POS.has(g.pos)) errors.push(`bad pos '${g.pos}' for '${expected}'`);
  const defWords = String(g.def || '').split(/\s+/).filter(Boolean);
  if (defWords.length < 4 || defWords.length > 20) errors.push(`def length ${defWords.length} for '${expected}'`);
  if (!g.bengali || !/[\u0980-\u09FF]/.test(g.bengali)) errors.push(`missing Bengali script for '${expected}'`);
  if (!Array.isArray(g.forms)) errors.push(`forms not array for '${expected}'`);
  else if (g.forms.some((f) => f.toLowerCase() === expected.toLowerCase())) errors.push(`forms contains headword for '${expected}'`);
  const sent = String(g.sentence || '');
  const sentWords = sent.split(/\s+/).filter(Boolean).length;
  if (sentWords < 6 || sentWords > 24) errors.push(`sentence length ${sentWords} for '${expected}'`);
  const hay = ` ${sent.toLowerCase().replace(/[^a-z0-9\s-]/g, ' ')} `;
  const targets = [expected.toLowerCase(), ...(g.forms || []).map((f) => f.toLowerCase())];
  if (!targets.some((t) => hay.includes(` ${t} `) || hay.includes(` ${t}s `) || hay.includes(` ${t}ed `) || hay.includes(` ${t}ing `))) {
    errors.push(`sentence missing word/form for '${expected}'`);
  }
  const id = slug(expected);
  if (seenSlugs.has(id)) errors.push(`duplicate slug '${id}'`);
  seenSlugs.add(id);
}

if (errors.length > 0) {
  console.error(`VALIDATION FAILED (${errors.length}):`);
  for (const e of errors.slice(0, 40)) console.error(' -', e);
  process.exit(1);
}

// Emit typed dataset module + manifest
const records = all.map((g, i) => ({
  id: slug(g.word),
  word: g.word,
  rank: words[i].rank,
  stage: Math.floor((words[i].rank - 1) / 50),
  bengali: g.bengali,
  pos: [g.pos],
  shortDefinition: g.def,
  forms: g.forms,
  sentence: g.sentence,
  topics: [],
}));

const fmt = (s) => JSON.stringify(s);
const ts =
  `// AUTO-GENERATED by scripts/merge-glosses.mjs — do not edit by hand.\n` +
  `// Source of truth: word.md (headwords + rank order) + src/data/glosses/* (study glosses).\n` +
  `import type { WordRecord } from '../types/domain';\n\n` +
  `export const WORDS: WordRecord[] = [\n` +
  records.map((r) => `  { id: ${fmt(r.id)}, word: ${fmt(r.word)}, rank: ${r.rank}, stage: ${r.stage}, bengali: ${fmt(r.bengali)}, pos: ${fmt(r.pos)}, shortDefinition: ${fmt(r.shortDefinition)}, forms: ${fmt(r.forms)}, sentence: ${fmt(r.sentence)}, topics: [] },`).join('\n') +
  `\n];\n\n` +
  `export const WORD_COUNT = ${records.length};\n` +
  `export const STAGE_COUNT = 10;\n` +
  `export const WORDS_PER_STAGE = 50;\n` +
  `export const WORD_MAP: Record<string, WordRecord> = Object.fromEntries(WORDS.map((w) => [w.id, w]));\n`;
writeFileSync(join(root, 'src', 'data', 'words.ts'), ts, 'utf8');
console.log(`OK: ${records.length} records validated, src/data/words.ts written.`);
